# 当代码推动到 master 分支时，执行当前工作流程

name: deploy serverless

on: #监听的事件和分支配置
  push:
    branches:
      - master 

jobs:
  test: #配置单元测试
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: unit test
        run: '' 
  deploy:
    name: deploy serverless
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: clone local repository
        uses: actions/checkout@v2
      - name: install serverless
        run: npm install -g serverless-cloud-framework
      - name: install dependency
        run: npm install
      - name: build
        run: npm build
      - name: deploy serverless
        run: scf deploy --debug
        env: # 环境变量
          STAGE: dev #您的部署环境
          SERVERLESS_PLATFORM_VENDOR: tencent #serverless 配置为腾讯
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }} 
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }} 
